-- MySQL Script generated by MySQL Workbench
-- Wed May 16 01:43:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mailbox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mailbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mailbox` DEFAULT CHARACTER SET utf8 ;
USE `mailbox` ;

-- -----------------------------------------------------
-- Table `mailbox`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mailbox`.`user` ;

CREATE TABLE IF NOT EXISTS `mailbox`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mailbox`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mailbox`.`email` ;

CREATE TABLE IF NOT EXISTS `mailbox`.`email` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `from_user_id` INT NOT NULL,
  `sent_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_email_user_idx` (`from_user_id` ASC),
  CONSTRAINT `fk_email_user`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `mailbox`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mailbox`.`email_to`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mailbox`.`email_to` ;

CREATE TABLE IF NOT EXISTS `mailbox`.`email_to` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `read` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_email_to_email_idx` (`email_id` ASC),
  INDEX `fk_email_to_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_email_to_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `mailbox`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_to_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mailbox`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mailbox`.`email_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mailbox`.`email_reply` ;

CREATE TABLE IF NOT EXISTS `mailbox`.`email_reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_email_id` INT NOT NULL,
  `reply_email_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_email_reply_parent_email_idx` (`parent_email_id` ASC),
  INDEX `fk_email_reply_reply_email_idx` (`reply_email_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_email_reply_parent_email`
    FOREIGN KEY (`parent_email_id`)
    REFERENCES `mailbox`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_reply_reply_email`
    FOREIGN KEY (`reply_email_id`)
    REFERENCES `mailbox`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mailbox`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mailbox`.`attachment` ;

CREATE TABLE IF NOT EXISTS `mailbox`.`attachment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` BLOB NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_attachment_email_idx` (`email_id` ASC),
  CONSTRAINT `fk_attachment_email`
    FOREIGN KEY (`email_id`)
    REFERENCES `mailbox`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
